### ISSUE TITLE
Is there is a way to make "Controlled Components"?

### ISSUE THREAD

**Issue by standy** [trueadm/mobx-inferno#3]
Im trying to make an input value be observable, and set an observable from input events, similar to React's [Controlled Components](https://facebook.github.io/react/docs/forms.html#controlled-components). But no changes in value and even event not firing. 

Example here (made from inferno-starter)
```
@observer
class ControlledInput extends Component {
    @observable val = 'val';

    render() {
        return <input type="text" 
                      onInput={e => this.val = e.target.value}
                      value={this.val} />;
    }
}
```

Is there is workaround, or this is just a bug?
Using beta31

**Comment by trueadm** [comment]
@standy This should work as expected, are you using `inferno-mobx`? `mobx-inferno` is for the older 0.7 of Inferno. Do you get any errors? If you put a debugger inside the callback, does the `this.val` get updated correctly?

**Comment by standy** [comment]
Did minimal repo to reproduce
https://github.com/standy/inferno-test

Inferno-mobx beta31
No errors
Callback just do not fire when i put `value` attribute

**Comment by trueadm** [comment]
@standy thanks, I'll check that out now :)

**Comment by trueadm** [comment]
@standy You need to use the latest `babel-plugin-inferno`, try: `@beta13`

**Comment by trueadm** [comment]
`"babel-plugin-inferno": "1.2.0-beta13"` works for me on your demo :)

**Comment by standy** [comment]
It works! Thank you
